/* QA only. No network requests, real tiles, keys, or Street View. */
(() => {
const pos = p => ({lat: typeof p?.lat==='function'?p.lat():Number(p?.lat)||0,lng:typeof p?.lng==='function'?p.lng():Number(p?.lng)||0});
class LatLng {constructor(a,b){const p=typeof a==='object'?pos(a):{lat:a,lng:b};this.a=p.lat;this.b=p.lng;}lat(){return this.a;}lng(){return this.b;}toJSON(){return{lat:this.a,lng:this.b};}}
class Emitter {constructor(){this.events={};}addListener(n,fn){(this.events[n]??=[]).push(fn);return{remove:()=>this.events[n]=this.events[n].filter(x=>x!==fn)};}emit(n,args){(this.events[n]||[]).slice().forEach(fn=>fn(args));}}
const event={trigger:(o,n,a)=>o?.emit?.(n,a),removeListener:l=>l?.remove?.(),clearInstanceListeners:o=>{o.events={};},addListenerOnce:(o,n,f)=>{let l=o.addListener(n,(...a)=>{l.remove();f(...a)});return l;}};
class Bounds {constructor(){this.points=[];}extend(p){this.points.push(pos(p));return this;}toJSON(){return{south:Math.min(...this.points.map(p=>p.lat)),north:Math.max(...this.points.map(p=>p.lat)),west:Math.min(...this.points.map(p=>p.lng)),east:Math.max(...this.points.map(p=>p.lng))};}}
class MapMock extends Emitter {
 constructor(el,options){super();this.el=el;this.opts=options;this.center=new LatLng(options.center);this.zoom=options.zoom;this.shapes=[];this.fitCalls=[];this.bounds={north:70,south:-40,west:-100,east:160};this.render();el.addEventListener('click',e=>this.emit('click',{latLng:new LatLng(48.86+(e.offsetY/el.clientHeight-.5),2.35+(e.offsetX/el.clientWidth-.5))}));window.__qaMapCount=(window.__qaMapCount||0)+1;}
 setOptions(o){Object.assign(this.opts,o);}getCenter(){return this.center;}setCenter(c){this.center=new LatLng(c);this.render();}getZoom(){return this.zoom;}setZoom(z){this.zoom=z;this.render();}getBounds(){return this.bounds;}
 fitBounds(b,pad){this.bounds=b.toJSON?b.toJSON():b;this.fitCalls.push({bounds:this.bounds,pad});this.center=new LatLng({lat:(this.bounds.north+this.bounds.south)/2,lng:(this.bounds.east+this.bounds.west)/2});this.render();setTimeout(()=>this.emit('idle'),0);}
 render(){if(this.scheduled)return;this.scheduled=true;requestAnimationFrame(()=>{this.scheduled=false;const b=this.bounds;let dx=(b.east-b.west+360)%360||360,dy=Math.max(.002,b.north-b.south);const pt=p=>{p=pos(p);return [80+((p.lng-b.west+360)%360)/dx*840,60+(b.north-p.lat)/dy*480];};
 const shapes=this.shapes.map(s=>{if(s.opts.path&&Array.isArray(s.opts.path)){let points=s.opts.path.map(p=>pt(p).join(',')).join(' ');return`<polyline points="${points}" fill="none" stroke="${s.opts.strokeColor||'#ed3c6b'}" stroke-width="3"/>`;}
 if(s.opts.position){const [x,y]=pt(s.opts.position);return`<g transform="translate(${x} ${y})"><circle r="13" fill="${s.opts.icon?.fillColor||'#39bdd5'}" stroke="white" stroke-width="3"/><text text-anchor="middle" dy="4" font-size="12" font-family="sans-serif" font-weight="700" fill="white">${s.opts.label?.text||''}</text></g>`;}return'';}).join('');
 this.el.innerHTML=`<svg width="100%" height="100%" viewBox="0 0 1000 600" preserveAspectRatio="none" aria-label="Carte simulee pour les tests"><defs><pattern id="qaGrid" width="100" height="75" patternUnits="userSpaceOnUse"><path d="M 100 0 L 0 0 0 75" fill="none" stroke="#9ebec1" stroke-width="1"/></pattern></defs><rect width="1000" height="600" fill="#cbdde0"/><path d="M40 60L170 30 290 200 215 280 315 430 240 510 70 470Z M580 80L870 30 955 235 875 430 720 515 560 425 460 270Z" fill="#e8e9dd" stroke="#b1bbb0" stroke-width="2"/><rect width="1000" height="600" fill="url(#qaGrid)"/>${shapes}<text x="500" y="575" text-anchor="middle" font-size="14" fill="#546f7a" font-family="sans-serif">QA : CARTE SIMULEE - AUCUNE TUILE GOOGLE</text></svg>`;});}
}
class Shape extends Emitter {constructor(opts){super();this.opts={...opts};this.map=null;this.setMap(opts.map);}setMap(m){if(this.map){this.map.shapes=this.map.shapes.filter(s=>s!==this);this.map.render();}this.map=m;if(m){m.shapes.push(this);m.render();}}setPosition(p){this.opts.position=pos(p);this.map?.render();}getPosition(){return new LatLng(this.opts.position);}setPath(p){this.opts.path=p;this.map?.render();}setOptions(o){Object.assign(this.opts,o);this.map?.render();}}
class Panorama extends Emitter {constructor(el,options){super();this.el=el;this.opts={...options};this.pov={heading:0,pitch:0};this.zoom=0;this.pano='qa';this.location={lat:48.86,lng:2.35};el.style.background=`linear-gradient(90deg,#15314155,#061d3022),url("${window.__qaPanorama||''}") center/cover`;el.setAttribute('aria-label','Panorama simule pour les tests');}
 getPano(){return this.pano;}setPano(v){this.pano=v;this.emit('pano_changed');}getPov(){return this.pov;}setPov(v){this.pov={...v};this.emit('pov_changed');}getZoom(){return this.zoom;}setZoom(v){this.zoom=v;this.emit('zoom_changed');}getPosition(){return new LatLng(this.location);}setPosition(p){this.location=pos(p);this.emit('position_changed');}setVisible(v){this.visible=v;}getVisible(){return this.visible;}setOptions(o){Object.assign(this.opts,o);}getLinks(){return[{heading:0,pano:'qa-neighbor'}];}}
class Service {async getPanorama(o){return{data:{location:{pano:o.pano||'qa-pano',description:'Lieu de test',latLng:new LatLng(48.86,2.35)},links:[{pano:'qa-next',heading:0}]}};}}
window.google={maps:{Map:MapMock,StreetViewPanorama:Panorama,StreetViewService:Service,Marker:Shape,Polyline:Shape,Polygon:Shape,Circle:Shape,LatLng,LatLngBounds:Bounds,event,SymbolPath:{CIRCLE:0},StreetViewPreference:{NEAREST:0},StreetViewSource:{GOOGLE:0}}};
window.__qaTicks=[];
})();
